In [2]:
import numpy as np

In [3]:
# 1D Array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.ndim

1

In [5]:
# 2D Array
ab = np.array([[1, 2, 3], [4, 5, 6]])
ab

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 3D Array
abc = np.array([[[1, 2, 3], [2, 3, 4]],
                [[3, 4, 5], [4, 5, 6]],
              [[7, 8, 9], [8, 9, 0]]])

In [7]:
abc

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[7, 8, 9],
        [8, 9, 0]]])

In [8]:
# checking the dimension of the array using ndim
abc.ndim

3

In [9]:
# shape of the array
abc.shape

(3, 2, 3)

In [10]:
# reshape
a1 = abc.reshape(3, 6)

In [11]:
a1

array([[1, 2, 3, 2, 3, 4],
       [3, 4, 5, 4, 5, 6],
       [7, 8, 9, 8, 9, 0]])

In [12]:
# flatten
ab.flatten()

array([1, 2, 3, 4, 5, 6])

In [13]:
# ravel
ab.ravel()

array([1, 2, 3, 4, 5, 6])

In [14]:
# checking size of array
ab.size

6

In [15]:
a = np.array([1, 2, 3, 4], ndmin=5)

print(a)
print("Shape:", a.shape)
print("Dimensions:", a.ndim)

[[[[[1 2 3 4]]]]]
Shape: (1, 1, 1, 1, 4)
Dimensions: 5


In [16]:
# Ones
temp_two = np.ones((3, 3))
temp_two

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# zeros function

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# eye functiom

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# identity function

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# sorting the array in ascending order and descending order

array = np.array([2, 5, 3, 1, 4])
print("Sorted in ascending order: ")
print(np.sort(array))
print("Sorting in descending order: ")
print(np.sort(array)[::-1])

Sorted in ascending order: 
[1 2 3 4 5]
Sorting in descending order: 
[5 4 3 2 1]


In [22]:
print("Mean: ", np.mean(array))
print("Median: ", np.median(array))
print("Standard Deviation: ", np.std(array))
print("Variance: ", np.var(array))
print("ptp: ", np.ptp(array))

Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Variance:  2.0
ptp:  4


In [23]:
array.size

5

In [26]:
np.random.normal(2, 1, 10)

array([2.22049799, 3.19550464, 3.04649084, 3.32680284, 3.54289292,
       4.31504777, 2.53354665, 1.65172825, 3.16344186, 1.30352679])

In [27]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])