# Experiment 1

## Assignment 1

In [1]:
import numpy as np

In [17]:
# function for addition
def add(a, b):
  return a + b

In [18]:
# function for subtraction
def subtract(a, b):
  return a-b

In [19]:
# function for multiplication
def multiply(a, b):
  return a*b

In [20]:
# function for division
def divide(a, b):
  return a / b

In [21]:
# function for dot product
def dot_product(a, b):
  return np.dot(a, b)

In [22]:
# declaring two arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [8]:
print("Matrix A:")
print(A)
print("Matrix B")
print(B)
print("Matrix Addition")
print(add(A, B))
print("Matrix Subtraction")
print(subtract(A, B))
print("Matrix Multiplication")
print(multiply(A, B))
print("Matrix Dot Product")
print(dot_product(A, B))
print("Matrix Divide")
print(divide(A, B))

Matrix A:
[[1 2]
 [3 4]]
Matrix B
[[5 6]
 [7 8]]
Matrix Addition
[[ 6  8]
 [10 12]]
Matrix Subtraction
[[-4 -4]
 [-4 -4]]
Matrix Multiplication
[[ 5 12]
 [21 32]]
Matrix Dot Product
[[19 22]
 [43 50]]
Matrix Divide
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Assignment 2

In [9]:
C = np.array([[1, 2],
 [3, 4]])

In [23]:
# Determinant
print("Matrix C:\n", C)
print("Determinant:\n", np.linalg.det(C))

Matrix C:
 [[1 2]
 [3 4]]
Determinant:
 -2.0000000000000004


In [24]:
# Inverse of Matrix
print("Inverse of Matrix: ")
np.linalg.inv(C)

Inverse of Matrix: 


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
# Transpose of Matrix
print("Transpose of Matrix (using linalg):")
np.linalg.matrix_transpose(C)

Transpose of Matrix (using linalg):


array([[1, 3],
       [2, 4]])

In [26]:
# Transpose of Matrix (Direct Method)
print("Transpose of Matrix (Direct Method):")
np.transpose(C)

Transpose of Matrix (Direct Method):


array([[1, 3],
       [2, 4]])